---
- hosts: "{{ target }}" #for Jenkins builds
# - hosts: instances #for manual builds
  become: false #runs all commands as ec2-user
  
  tasks:
  
  - name: Get info on docker host and list containers
    community.docker.docker_host_info:
      containers: true
    register: ansible_containers

  - name: Get info on docker host and list images
    community.docker.docker_host_info:
      images: true
    register: ansible_images

  # - name: Print info on docker host
  #   debug:
  #     var: ansible_containers

  # - name: Print info on docker host
  #   debug:
  #     var: ansible_images

  - name: Stop all running containers
    docker_container:
      name: "{{ item.Names[0] }}"
      state: stopped
    with_items: "{{ ansible_containers.containers }}"

  - name: Prune all docker resources
    community.docker.docker_prune:
      containers: true
      images: true
      images_filters:
        dangling: false
      networks: true
      volumes: true
      builder_cache: true
